python: /home/earthtest/miniconda3/envs/base_env/bin/python
perl: /home/earthtest/miniconda3/envs/base_env/bin/perl
rscript: /home/earthtest/miniconda3/envs/R/bin/Rscript
fastqc: /home/earthtest/miniconda3/envs/base_env/bin/fastqc
fastp: /home/earthtest/miniconda3/envs/base_env/bin/fastp
bowtie2: /home/earthtest/miniconda3/envs/base_env/bin/bowtie2
blastn: /home/earthtest/miniconda3/envs/base_env/bin/blastn
samtools: /home/earthtest/miniconda3/envs/base_env/bin/samtools
parallel: /home/earthtest/miniconda3/envs/denovo/bin/parallel
mafft: /home/earthtest/miniconda3/envs/microbial_wgs/bin/mafft
fasttree: /home/earthtest/miniconda3/envs/microbial_wgs/bin/fasttree
guppy: /opt/ont-guppy-cpu/bin/guppy_basecaller

# 个人软件/模块
GDHR: /sdbb/share/lib/GDHR